from django import forms


class CursoFormulario(forms.Form):
    codigo=forms.IntegerField()
    Nombre_Titanio=forms.CharField()
    Titanio=forms.IntegerField()
    Nombre_Amarillo_Bayer=forms.CharField()
    Amarillo_Bayer=forms.IntegerField()
    Nombre_Amarillo_Vivo=forms.CharField()
    Amarillo_Vivo=forms.IntegerField()
    Nombre_Amarillo_AL90=forms.CharField()
    Amarillo_AL90=forms.IntegerField()   
    Nombre_Azul=forms.CharField()
    Azul=forms.IntegerField()
    Nombre_Rojo_Bayer=forms.CharField()
    Rojo_Bayer=forms.IntegerField()
    Nombre_Rojo_Vivo=forms.CharField()
    Rojo_Vivo=forms.IntegerField()
    Nombre_Negro=forms.CharField()
    Negro=forms.IntegerField()
    Nombre_Tinta_Azul=forms.CharField()
    Tinta_Azul=forms.IntegerField()
    Nombre_Tinta_Verde=forms.CharField()
    Tinta_Verde=forms.IntegerField()
    Nombre_Tinta_Roja=forms.CharField()
    Tinta_Roja=forms.IntegerField()
    Nombre_Tinta_Violeta=forms.CharField()
    Tinta_Violeta=forms.IntegerField()
    Nombre_Tinta_Fucsia=forms.CharField()
    Tinta_Fucsia=forms.IntegerField()
    Agua=forms.IntegerField()
    Resina=forms.IntegerField()
    Talco=forms.IntegerField()
    Arena=forms.IntegerField()
    Celulosa=forms.IntegerField()
    Cuarzo=forms.IntegerField()
    AntiBacterial=forms.IntegerField()
    AntiEspumante=forms.IntegerField()


class EmpleadosFormulario(forms.Form):
    Cedula=forms.IntegerField()
    Nombres=forms.CharField()
    Apellidos=forms.CharField()
    Cargo=forms.CharField()
    Año_Nacimiento=forms.IntegerField()
    RH=forms.CharField()

class PinturaFormulario(forms.Form):
    codigo_2=forms.IntegerField()
    Nombre_Titanio_2=forms.CharField()
    Titanio_2=forms.IntegerField()
    Nombre_Amarillo_Bayer_2=forms.CharField()
    Amarillo_Bayer_2=forms.IntegerField()
    Nombre_Amarillo_Vivo_2=forms.CharField()
    Amarillo_Vivo_2=forms.IntegerField()
    Nombre_Amarillo_AL90_2=forms.CharField()
    Amarillo_AL90_2=forms.IntegerField()   
    Nombre_Azul_2=forms.CharField()
    Azul_2=forms.IntegerField()
    Nombre_Rojo_Bayer_2=forms.CharField()
    Rojo_Bayer_2=forms.IntegerField()
    Nombre_Rojo_Vivo_2=forms.CharField()
    Rojo_Vivo_2=forms.IntegerField()
    Nombre_Negro_2=forms.CharField()
    Negro_2=forms.IntegerField()
    Nombre_Tinta_Azul_2=forms.CharField()
    Tinta_Azul_2=forms.IntegerField()
    Nombre_Tinta_Verde_2=forms.CharField()
    Tinta_Verde_2=forms.IntegerField()
    Nombre_Tinta_Roja_2=forms.CharField()
    Tinta_Roja_2=forms.IntegerField()
    Nombre_Tinta_Violeta_2=forms.CharField()
    Tinta_Violeta_2=forms.IntegerField()
    Nombre_Tinta_Fucsia_2=forms.CharField()
    Tinta_Fucsia_2=forms.IntegerField()
    Agua_2=forms.IntegerField()
    Resina_2=forms.IntegerField()
    Talco_2=forms.IntegerField()
    Celulosa_2=forms.IntegerField()
    AntiBacterial_2=forms.IntegerField()
    AntiEspumante_2=forms.IntegerField()